### ISSUE TITLE
Unserializable items in the 'changes' set make the CRUD handler get stuck in 'updating'

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta-core#3470]
When reading back a resource, if any of the fields is set to a Set, this cause the crud handler to fail, in such a way that the error is not reported (i.e. this goes straight through all surrounding safeties) 

# Problem
```
2021-11-17 20:02:05,997 ERROR    inmanta.util Unable to serialize set()
2021-11-17 20:02:05,997 ERROR    inmanta.agent.agent.hashicorp-helm-2.4.1 resource terraform::Resource[hashicorp-helm-2.4.1,id=hashicorp-helm-2.4.1-helm_release-test],v=31: An error occurred during deployment of terraform::Resource[hashicorp-helm-2.4.1,id=hashicorp-helm-2.4.1-helm_release-test],v=31 (exception: Exception('Exception during serializing log message arguments'))
Traceback (most recent call last):
  File "/home/wouter/.virtualenvs/uc2/lib64/python3.8/site-packages/inmanta/agent/handler.py", line 366, in log_msg
    json_encode(kwargs)
  File "/home/wouter/.virtualenvs/uc2/lib64/python3.8/site-packages/inmanta/protocol/common.py", line 902, in json_encode
    return json.dumps(value, default=custom_json_encoder).replace("</", "<\\/")
  File "/usr/lib64/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib64/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/wouter/.virtualenvs/uc2/lib64/python3.8/site-packages/inmanta/protocol/common.py", line 886, in custom_json_encoder
    return util.api_boundary_json_encoder(o)
  File "/home/wouter/.virtualenvs/uc2/lib64/python3.8/site-packages/inmanta/util.py", line 259, in api_boundary_json_encoder
    return custom_json_encoder(o)
  File "/home/wouter/.virtualenvs/uc2/lib64/python3.8/site-packages/inmanta/util.py", line 291, in custom_json_encoder
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: set() is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/wouter/.virtualenvs/uc2/lib64/python3.8/site-packages/inmanta/agent/handler.py", line 915, in execute
    ctx.debug("Calling update_resource", changes=changes)
  File "/home/wouter/.virtualenvs/uc2/lib64/python3.8/site-packages/inmanta/agent/handler.py", line 384, in debug
    self.log_msg(logging.DEBUG, msg, args, kwargs)
  File "/home/wouter/.virtualenvs/uc2/lib64/python3.8/site-packages/inmanta/agent/handler.py", line 368, in log_msg
    raise Exception("Exception during serializing log message arguments") from e
Exception: Exception during serializing log message arguments
2021-11-17 20:02:06,004 ERROR    inmanta.util Unable to serialize set()
2021-11-17 20:02:06,004 ERROR    inmanta.util An exception occurred while handling a future: set() is not JSON serializable
Traceback (most recent call last):
  File "/home/wouter/.virtualenvs/uc2/lib64/python3.8/site-packages/inmanta/util.py", line 301, in handle_result
    f.result()
  File "/home/wouter/.virtualenvs/uc2/lib64/python3.8/site-packages/inmanta/agent/agent.py", line 307, in execute
    response = await self.scheduler.get_client().resource_action_update(
  File "/home/wouter/.virtualenvs/uc2/lib64/python3.8/site-packages/inmanta/protocol/endpoints.py", line 433, in _call
    result = await self._transport_instance.call(method_properties, args, kwargs)
  File "/home/wouter/.virtualenvs/uc2/lib64/python3.8/site-packages/inmanta/protocol/rest/client.py", line 111, in call
    zipped, body = common.gzipped_json(body)
  File "/home/wouter/.virtualenvs/uc2/lib64/python3.8/site-packages/inmanta/protocol/common.py", line 906, in gzipped_json
    json_string = json_encode(value)
  File "/home/wouter/.virtualenvs/uc2/lib64/python3.8/site-packages/inmanta/protocol/common.py", line 902, in json_encode
    return json.dumps(value, default=custom_json_encoder).replace("</", "<\\/")
  File "/usr/lib64/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib64/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/wouter/.virtualenvs/uc2/lib64/python3.8/site-packages/inmanta/protocol/common.py", line 886, in custom_json_encoder
    return util.api_boundary_json_encoder(o)
  File "/home/wouter/.virtualenvs/uc2/lib64/python3.8/site-packages/inmanta/util.py", line 259, in api_boundary_json_encoder
    return custom_json_encoder(o)
  File "/home/wouter/.virtualenvs/uc2/lib64/python3.8/site-packages/inmanta/util.py", line 291, in custom_json_encoder
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: set() is not JSON serializable
```

**Comment by wouterdb** [comment]
1. We should try to serialize these changes earlier in the process 
2. if they don't pass sanitation, turn them into strings
3. we should update pytest-inmanta to check in finilize context of invalid items are pressent.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/3470?planning-poker) with ZenHub @andraskvr @arnaudsjs @FloLey @Hugo-Inmanta @sanderr
