### ISSUE TITLE
KeyError during compile just prints the missing key

### ISSUE THREAD

**Issue by edvgui** [inmanta/inmanta-core#3787]
If the compiler encounters a `KeyError` when compiling the model, it will just print the missing key, which is quite confusing:
```console
(quickstart) guillaume@latitude-5411:~/Documents/quickstart-project$ inmanta export
'ji'
(quickstart) guillaume@latitude-5411:~/Documents/quickstart-project$ inmanta export -X
Traceback (most recent call last):
  File "/home/guillaume/.virtualenvs/quickstart/lib/python3.9/site-packages/inmanta/app.py", line 781, in app
    options.func(options)
  File "/home/guillaume/.virtualenvs/quickstart/lib/python3.9/site-packages/inmanta/app.py", line 561, in export
    results = export.run(
  File "/home/guillaume/.virtualenvs/quickstart/lib/python3.9/site-packages/inmanta/export.py", line 332, in run
    self._load_resources(types)
  File "/home/guillaume/.virtualenvs/quickstart/lib/python3.9/site-packages/inmanta/export.py", line 171, in _load_resources
    res = Resource.create_from_model(self, entity, DynamicProxy.return_value(instance))
  File "/home/guillaume/.virtualenvs/quickstart/lib/python3.9/site-packages/inmanta/resources.py", line 331, in create_from_model
    fields = {field: resource_cls.map_field(exporter, entity_name, field, model_object) for field in resource_cls.fields}
  File "/home/guillaume/.virtualenvs/quickstart/lib/python3.9/site-packages/inmanta/resources.py", line 331, in <dictcomp>
    fields = {field: resource_cls.map_field(exporter, entity_name, field, model_object) for field in resource_cls.fields}
  File "/home/guillaume/.virtualenvs/quickstart/lib/python3.9/site-packages/inmanta/resources.py", line 301, in map_field
    value = mthd(exporter, model_object)
  File "/home/guillaume/Documents/quickstart-project/libs/yang/plugins/__init__.py", line 986, in get_xml
    return etree.tounicode(yang_resource_helper.serialize(), pretty_print=True)
  File "/home/guillaume/Documents/quickstart-project/libs/yang/plugins/__init__.py", line 812, in serialize
    return self.serializer.serialize(self._root_container)
  File "/home/guillaume/Documents/quickstart-project/libs/yang/plugins/__init__.py", line 314, in serialize
    self._serialize_container(child, root_xml)
  File "/home/guillaume/Documents/quickstart-project/libs/yang/plugins/__init__.py", line 379, in _serialize_container
    self._serialize_container(child, xml, operation)
  File "/home/guillaume/Documents/quickstart-project/libs/yang/plugins/__init__.py", line 337, in _serialize_container
    namespaces = self._determine_namespaces(container_node, parent_xml)
  File "/home/guillaume/Documents/quickstart-project/libs/yang/plugins/__init__.py", line 456, in _determine_namespaces
    namespaces[None] = self._root_namespaces[module_namespace_name]
KeyError: 'ji'
 ```

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/3787?planning-poker) with ZenHub @arnaudsjs @bartv @FloLey @Hugo-Inmanta @sanderr

**Comment by edvgui** [comment]
[issue_3787.zip](https://github.com/inmanta/inmanta-core/files/8098134/issue_3787.zip)
