### ISSUE TITLE
Creating token when authentication is not enabled makes the server crash (temporarily)

### ISSUE THREAD

**Issue by edvgui** [inmanta/inmanta-core#3900]
The server was unreachable for about 3 minutes, then we could see this in the logs:
```
2022-02-24 12:33:29,623 ERROR    tornado.access 500 POST /api/v1/environment_auth (192.168.25.6) 262051.11ms
2022-02-24 12:35:40,693 ERROR    inmanta.protocol.rest An exception occured during the request.
Traceback (most recent call last):
  File "/usr/lib64/python3.6/urllib/request.py", line 1349, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib64/python3.6/http/client.py", line 1269, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1315, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1264, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 978, in send
    self.connect()
  File "/usr/lib64/python3.6/http/client.py", line 1429, in connect
    super().connect()
  File "/usr/lib64/python3.6/http/client.py", line 950, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib64/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib64/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/inmanta/lib64/python3.6/site-packages/inmanta/config.py", line 589, in validate_rs265
    with request.urlopen(self.jwks_uri, context=ctx) as response:
  File "/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 1392, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python3.6/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/inmanta/lib64/python3.6/site-packages/inmanta/protocol/rest/__init__.py", line 488, in _execute_call
    result = await config.handler(**arguments.call_args)
  File "/opt/inmanta/lib64/python3.6/site-packages/inmanta/server/services/environmentservice.py", line 262, in create_token
    return 200, {"token": await self.environment_create_token(env, client_types, idempotent)}
  File "/opt/inmanta/lib64/python3.6/site-packages/inmanta/server/services/environmentservice.py", line 475, in environment_create_token
    return encode_token(client_types, str(env.id), idempotent)
  File "/opt/inmanta/lib64/python3.6/site-packages/inmanta/protocol/common.py", line 928, in encode_token
    cfg = inmanta_config.AuthJWTConfig.get_sign_config()
  File "/opt/inmanta/lib64/python3.6/site-packages/inmanta/config.py", line 475, in get_sign_config
    cls.list()
  File "/opt/inmanta/lib64/python3.6/site-packages/inmanta/config.py", line 439, in list
    obj = cls(name, section, cfg[section])
  File "/opt/inmanta/lib64/python3.6/site-packages/inmanta/config.py", line 507, in __init__
    self.validate_rs265()
  File "/opt/inmanta/lib64/python3.6/site-packages/inmanta/config.py", line 595, in validate_rs265
    "Unable to load key data for %s using the provided jwks_uri. Got error: %s" % (self.section, e.response)
AttributeError: 'URLError' object has no attribute 'response'
```

![image](https://user-images.githubusercontent.com/20844316/155526678-2adb2fbf-19a1-477e-b210-b9125b0c3a76.png)

**Comment by edvgui** [comment]
Here is the config of the server:

<details>

<summary>inmanta.cfg</summary>

```cfg
# The directory where the server stores its state
state-dir=/var/lib/inmanta

# The directory where the server stores log file. Currently this is only for the output of
# embedded agents.
log-dir=/var/log/inmanta

fact-expire = 3600

# Force the hostname of this machine to a specific value
#node-name =

# Names of the agents this instance should deploy configuration for
agent-names = $node-name

# The deploy interval of the agent
agent_deploy_interval = 600

# The splaytime added to the agent_deploy_interval. Set this to 0 to disable splaytime
agent_deploy_splay_time = 600

# The repair interval of the agent
agent_repair_interval = 86400

# The splaytime added to the agent_repair_interval. Set this to 0 to disable splaytime
agent_repair_splay_time = 600

[database]
# The hostname of the database server
#host = localhost
# The port of the database server
#port = 5432
# The name of the database on the server
#name = inmanta
# The username to use to access the database
#username=
# The password to that belongs to the database user
#password=

[influxdb]
# The hostname of the influxdb server
# Enable metering by setting this value
#host = localhost
# The port of the influxdb server
#port = 8086
# The name of the database on the influxdb server
#name = inmanta
# The username to use to access influxdb
#username =
# The password to that belongs to the influxdb user
#password =
# The reporting interval
#interval = 30
# A dict of tags to attach to all influxdb records
#tags= environment=prod,az=a

[server]
# A comma-separated list of addresses on which the server will listen for connections
# ipv4 and ipv6 addresses are supported
bind-address = 127.0.0.1
# The port on which the server will listen for connections
bind-port = 8888

# The public ip address of the server. This is required for example to inject the inmanta agent in
# virtual machines at boot time.
#server_address=localhost

# After how many seconds will discovered facts/parameters expire
#fact-expire = 3600

# After how many seconds will discovered facts/parameters be renewed? This value needs to be lower
# than fact-expire
#fact-renew = 1200

# The number of seconds to wait before the server may attempt to do a new recompile. Recompiles are
# triggered after facts updates for example.
auto-recompile-wait = 10

# On boot and at regular intervals the server will purge versions that have not been deployed. This
# is the number of most recent undeployed versions to keep available.
#available-versions-to-keep=10

# The number of seconds between version purging
#purge-versions-interval=3600

# Cert and key file to enable ssl in the server. Both have to be set to enable SSL.
#ssl-cert-file=
#ssl-key-file=

# Configures the Access-Control-Allow-Origin setting of the http server
# can be a single item or a list of strings
# More on Access-Control-Allow-origin:
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin
#access-control-allow-origin = *

[agent_client_rest_transport]
host = localhost
port = 8888
#ssl=false
#ssl_ca_cert_file=

[dashboard]
# Host the dashboard from within the server. The server does not (yet) override the config.js file
# of the dashboard. This will need to be configured manually. The dashboard will be available
# on the server under /dashboard/
enabled=true
# The path where the dashboard is installed
path=/opt/inmanta/dashboard
```

</details>

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/3900?planning-poker) with ZenHub @andraskvr @arnaudsjs @bartv @FloLey @Hugo-Inmanta @sanderr
