### ISSUE TITLE
inmanta --version crashes

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta-core#4107]
```
(vylab) [rocky@workstation vylab]$ inmanta --version
Traceback (most recent call last):
  File "/usr/bin/inmanta", line 8, in <module>
    sys.exit(app())
  File "/opt/inmanta/lib64/python3.9/site-packages/inmanta/app.py", line 747, in app
    print_versions_installed_components_and_exit()
  File "/opt/inmanta/lib64/python3.9/site-packages/inmanta/app.py", line 645, in print_versions_installed_components_and_exit
    app_context = bootloader.load_slices()
  File "/opt/inmanta/lib64/python3.9/site-packages/inmanta/server/bootloader.py", line 170, in load_slices
    return self._collect_slices(exts)
  File "/opt/inmanta/lib64/python3.9/site-packages/inmanta/server/bootloader.py", line 162, in _collect_slices
    setup(myctx)
  File "src/inmanta_ext/lsm/extension.py", line 19, in setup
  File "src/inmanta_lsm/callback.py", line 57, in __init__
  File "/usr/lib64/python3.9/logging/__init__.py", line 1146, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib64/python3.9/logging/__init__.py", line 1175, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
PermissionError: [Errno 13] Permission denied: '/var/log/inmanta/callback.log'
```

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/4107?planning-poker) with ZenHub @andraskvr @arnaudsjs @FloLey @Hugo-Inmanta @sanderr
