### ISSUE TITLE
inmanta project install does not protect product's dependencies

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#4200]
# description
The `inmanta project install` command does an installation of module's dependencies in the active venv. It adds a constraint on the product or core package (depending on which are installed), pinning them to the currently installed version. However, the way `pip install` works, this apparently does not suffice to protect core's (or product's) dependencies.

Especially now that we've added a bunch of constraints to core and the extensions, this could be a real issue, because `inmanta project install` might reinstall these dependencies with incompatible versions, completely breaking the compiler, with no easy way to recover except for a reinstall of the product.

See constraints [collection](https://github.com/inmanta/inmanta-core/blob/e034212a3583b3f40f0123510d19dba1b82fa45b/src/inmanta/env.py#L297) and [application](https://github.com/inmanta/inmanta-core/blob/e034212a3583b3f40f0123510d19dba1b82fa45b/src/inmanta/env.py#L261).

# steps to reproduce
```
sander@bedevere:~$ export PIP_INDEX_URL=https://artifacts.internal.inmanta.com/inmanta/dev
sander@bedevere:~$ mktmpenv -p python3.9 --quiet
virtualenvwrapper.user_scripts creating /home/sander/.virtualenvs/tmp-b1d87119a0d1ea5/bin/predeactivate
virtualenvwrapper.user_scripts creating /home/sander/.virtualenvs/tmp-b1d87119a0d1ea5/bin/postdeactivate
virtualenvwrapper.user_scripts creating /home/sander/.virtualenvs/tmp-b1d87119a0d1ea5/bin/preactivate
virtualenvwrapper.user_scripts creating /home/sander/.virtualenvs/tmp-b1d87119a0d1ea5/bin/postactivate
virtualenvwrapper.user_scripts creating /home/sander/.virtualenvs/tmp-b1d87119a0d1ea5/bin/get_env_details
This is a temporary environment. It will be deleted when you run 'deactivate'.
(tmp-b1d87119a0d1ea5) sander@bedevere:~/.virtualenvs/tmp-b1d87119a0d1ea5$ pip install --quiet -U pip
(tmp-b1d87119a0d1ea5) sander@bedevere:~/.virtualenvs/tmp-b1d87119a0d1ea5$ pip install --quiet --pre inmanta-core
(tmp-b1d87119a0d1ea5) sander@bedevere:~/.virtualenvs/tmp-b1d87119a0d1ea5$ cookiecutter --no-input https://github.com/inmanta/inmanta-project-template
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /home/sander/.virtualenvs/tmp-b1d87119a0d1ea5/project/.git/
[master (root-commit) 0ea6628] initial commit: cookiecutter template
 4 files changed, 38 insertions(+)
 create mode 100644 .editorconfig
 create mode 100644 .gitignore
 create mode 100644 main.cf
 create mode 100644 project.yml
(tmp-b1d87119a0d1ea5) sander@bedevere:~/.virtualenvs/tmp-b1d87119a0d1ea5$ cd project/
(tmp-b1d87119a0d1ea5) sander@bedevere:~/.virtualenvs/tmp-b1d87119a0d1ea5/project$ echo "  - std==3.0.1" >> project.yml
(tmp-b1d87119a0d1ea5) sander@bedevere:~/.virtualenvs/tmp-b1d87119a0d1ea5/project$ pip list | grep Jinja
Jinja2             3.1.2
(tmp-b1d87119a0d1ea5) sander@bedevere:~/.virtualenvs/tmp-b1d87119a0d1ea5/project$ inmanta project install
(tmp-b1d87119a0d1ea5) sander@bedevere:~/.virtualenvs/tmp-b1d87119a0d1ea5/project$ pip list | grep Jinja
Jinja2             2.11.3
(tmp-b1d87119a0d1ea5) sander@bedevere:~/.virtualenvs/tmp-b1d87119a0d1ea5/project$ inmanta compile
Traceback (most recent call last):
  File "/home/sander/.virtualenvs/tmp-b1d87119a0d1ea5/bin/inmanta", line 5, in <module>
    from inmanta.app import app
  File "/home/sander/.virtualenvs/tmp-b1d87119a0d1ea5/lib/python3.9/site-packages/inmanta/app.py", line 56, in <module>
    from inmanta import const, module, moduletool, protocol
  File "/home/sander/.virtualenvs/tmp-b1d87119a0d1ea5/lib/python3.9/site-packages/inmanta/moduletool.py", line 36, in <module>
    from cookiecutter.main import cookiecutter
  File "/home/sander/.virtualenvs/tmp-b1d87119a0d1ea5/lib/python3.9/site-packages/cookiecutter/main.py", line 15, in <module>
    from cookiecutter.generate import generate_context, generate_files
  File "/home/sander/.virtualenvs/tmp-b1d87119a0d1ea5/lib/python3.9/site-packages/cookiecutter/generate.py", line 15, in <module>
    from jinja2 import FileSystemLoader
  File "/home/sander/.virtualenvs/tmp-b1d87119a0d1ea5/lib/python3.9/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/home/sander/.virtualenvs/tmp-b1d87119a0d1ea5/lib/python3.9/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/home/sander/.virtualenvs/tmp-b1d87119a0d1ea5/lib/python3.9/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/home/sander/.virtualenvs/tmp-b1d87119a0d1ea5/lib/python3.9/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/sander/.virtualenvs/tmp-b1d87119a0d1ea5/lib/python3.9/site-packages/markupsafe/__init__.py)
(tmp-b1d87119a0d1ea5) sander@bedevere:~/.virtualenvs/tmp-b1d87119a0d1ea5/project$ pip install --quiet -U Jinja2
(tmp-b1d87119a0d1ea5) sander@bedevere:~/.virtualenvs/tmp-b1d87119a0d1ea5/project$ inmanta compile
Hello world!
(tmp-b1d87119a0d1ea5) sander@bedevere:~/.virtualenvs/tmp-b1d87119a0d1ea5/project$ 
```

# suggested fix
The installation that is done now is `pip install -r requirements.txt -c <constraints_file_with_core_pinned>`. Adding `inmanta-core` as a requirement as well solves the issue: `pip install -r requirements.txt inmanta-core -c <constraints_file_with_core_pinned>` (or more compact, but not yet verified to work: `pip install -r requirements.txt inmanta-core==<current_version>`.

This would need to be done for all packages that compose the product, meaning any product or component that is already installed in the venv, rather than only the first of `inmanta-service-orchestrator`, `inmanta` or `inmanta-core`.  That would be `inmanta-*`and `inmanta` and excluding `inmanta-module-*`

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/4200?planning-poker) with ZenHub @andraskvr @arnaudsjs @FloLey @Hugo-Inmanta @sanderr
