### ISSUE TITLE
Syntax error when checking if dict value is defined

### ISSUE THREAD

**Issue by edvgui** [inmanta/inmanta-core#4317]
The following model raises a `inmanta.parser.ParserException: Syntax error` while I would expect it to work:
```
d = {"a": "A", "b": null}

# This doesn't work
if "a" in d and d["a"] is defined:
    std::print(d["a"])
end
```

The error trace is the following:
```
Traceback (most recent call last):
  File "/home/guillaume/.virtualenvs/bics_ce/lib/python3.9/site-packages/inmanta/app.py", line 780, in app
    options.func(options)
  File "/home/guillaume/.virtualenvs/bics_ce/lib/python3.9/site-packages/inmanta/app.py", line 355, in compile_project
    do_compile()
  File "/home/guillaume/.virtualenvs/bics_ce/lib/python3.9/site-packages/inmanta/compiler/__init__.py", line 69, in do_compile
    compiler.handle_exception(e)
  File "/home/guillaume/.virtualenvs/bics_ce/lib/python3.9/site-packages/inmanta/compiler/__init__.py", line 248, in handle_exception
    self._handle_exception_export(e)
  File "/home/guillaume/.virtualenvs/bics_ce/lib/python3.9/site-packages/inmanta/compiler/__init__.py", line 254, in _handle_exception_export
    raise exception
  File "/home/guillaume/.virtualenvs/bics_ce/lib/python3.9/site-packages/inmanta/compiler/__init__.py", line 246, in handle_exception
    self._handle_exception_datatrace(exception)
  File "/home/guillaume/.virtualenvs/bics_ce/lib/python3.9/site-packages/inmanta/compiler/__init__.py", line 258, in _handle_exception_datatrace
    raise exception
  File "/home/guillaume/.virtualenvs/bics_ce/lib/python3.9/site-packages/inmanta/compiler/__init__.py", line 67, in do_compile
    (statements, blocks) = compiler.compile()
  File "/home/guillaume/.virtualenvs/bics_ce/lib/python3.9/site-packages/inmanta/compiler/__init__.py", line 188, in compile
    project.load()
  File "/home/guillaume/.virtualenvs/bics_ce/lib/python3.9/site-packages/inmanta/module.py", line 754, in load
    self.get_complete_ast()
  File "/home/guillaume/.virtualenvs/bics_ce/lib/python3.9/site-packages/inmanta/module.py", line 796, in get_complete_ast
    (statements, block) = self.get_ast()
  File "/home/guillaume/.virtualenvs/bics_ce/lib/python3.9/site-packages/inmanta/module.py", line 777, in get_ast
    self._ast_cache = self.__load_ast()
  File "/home/guillaume/.virtualenvs/bics_ce/lib/python3.9/site-packages/inmanta/module.py", line 812, in __load_ast
    return self._load_file(main_ns, os.path.join(self.project_path, self.main_file))
  File "/home/guillaume/.virtualenvs/bics_ce/lib/python3.9/site-packages/inmanta/module.py", line 575, in _load_file
    stmts = plyInmantaParser.parse(ns, file)
  File "/home/guillaume/.virtualenvs/bics_ce/lib/python3.9/site-packages/inmanta/parser/plyInmantaParser.py", line 1084, in parse
    statements = base_parse(namespace, filename, content)
  File "/home/guillaume/.virtualenvs/bics_ce/lib/python3.9/site-packages/inmanta/parser/plyInmantaParser.py", line 1065, in base_parse
    return parser.parse(data, lexer=lexer, debug=False)
  File "/home/guillaume/.virtualenvs/bics_ce/lib/python3.9/site-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/guillaume/.virtualenvs/bics_ce/lib/python3.9/site-packages/ply/yacc.py", line 1201, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/home/guillaume/.virtualenvs/bics_ce/lib/python3.9/site-packages/ply/yacc.py", line 192, in call_errorfunc
    r = errorfunc(token)
  File "/home/guillaume/.virtualenvs/bics_ce/lib/python3.9/site-packages/inmanta/parser/plyInmantaParser.py", line 1029, in p_error
    raise ParserException(r, str(p.value), "invalid identifier, %s is a reserved keyword" % p.value)
inmanta.parser.ParserException: Syntax error: invalid identifier, is is a reserved keyword (./main.cf:4:24)
```

Inmanta version is
```
Inmanta Service Orchestrator (Open Source Edition): 4.4.4.dev20220523033008
Compiler version: 2020.7.1
Extensions:
    * core: 4.4.4.dev20220523033008
```

An easy workaround is to do this:
```
d = {"a": "A", "b": null}

# This works
a = "a" in d
    ? d["a"]
    : null

if a is defined:
    std::print(a)
end
```

**Comment by edvgui** [comment]
Doing the following works as well, so I might just be doing a bad usage of the `defined` keyword?
```
d = {"a": "A", "b": null}

# This works
if "a" in d and d["a"] != null:
    std::print(d["a"])
end
```

**Comment by wouterdb** [comment]
`is defined` would work as `== null`
