### ISSUE TITLE
Confusing error when variable not found in implementation

### ISSUE THREAD

**Issue by edvgui** [inmanta/inmanta-core#4985]
```
entity A:
	bool condition
end


implementation a for A:
	if self.condition:
		value = 0
	else:
		value = 1
	end

	std::print(value)
end

implement A using a

A(condition=true)

```

Compiling the above model will show this exception:
```console
(tmp-af7dbc22f361108) guillaume@latitude-5411:~/.virtualenvs/tmp-af7dbc22f361108/confusing-error$ inmanta -X compile
Traceback (most recent call last):
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/app.py", line 870, in app
    options.func(options)
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/app.py", line 408, in compile_project
    do_compile()
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/compiler/__init__.py", line 76, in do_compile
    compiler.handle_exception(e)
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/compiler/__init__.py", line 250, in handle_exception
    self._handle_exception_export(e)
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/compiler/__init__.py", line 256, in _handle_exception_export
    raise exception
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/compiler/__init__.py", line 248, in handle_exception
    self._handle_exception_datatrace(exception)
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/compiler/__init__.py", line 260, in _handle_exception_datatrace
    raise exception
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/compiler/__init__.py", line 72, in do_compile
    success = sched.run(compiler, statements, blocks)
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/execute/scheduler.py", line 419, in run
    next.execute()
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/execute/runtime.py", line 923, in execute
    raise e
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/execute/runtime.py", line 919, in execute
    self._unsafe_execute()
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/execute/runtime.py", line 913, in _unsafe_execute
    value = self.expression.execute(requires, self.resolver, self.queue_scheduler)
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/ast/statements/generator.py", line 143, in execute
    xc.emit(myqueue)
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/execute/runtime.py", line 1105, in emit
    self.block.emit(self, queue)
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/ast/blocks.py", line 108, in emit
    raise e
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/ast/blocks.py", line 105, in emit
    s.emit(resolver, queue)
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/ast/statements/__init__.py", line 146, in emit
    reqs = self.requires_emit(resolver, queue)
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/ast/statements/call.py", line 96, in requires_emit
    sub = ReferenceStatement.requires_emit(self, resolver, queue)
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/ast/statements/__init__.py", line 477, in requires_emit
    requires.update({rk: rv for i in self.children for (rk, rv) in i.requires_emit(resolver, queue).items()})
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/ast/statements/__init__.py", line 477, in <dictcomp>
    requires.update({rk: rv for i in self.children for (rk, rv) in i.requires_emit(resolver, queue).items()})
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/ast/variables.py", line 80, in requires_emit
    requires[self.name] = resolver.lookup(self.full_name)
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/execute/runtime.py", line 1096, in lookup
    return self.resolver.lookup(name, root)
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/execute/runtime.py", line 1067, in lookup
    return self.parent.lookup(name, self.root)
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/execute/runtime.py", line 1096, in lookup
    return self.resolver.lookup(name, root)
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/execute/runtime.py", line 1032, in lookup
    return ns.lookup(name)
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/ast/__init__.py", line 326, in lookup
    return self.get_scope().direct_lookup(name)
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/execute/runtime.py", line 1102, in direct_lookup
    raise NotFoundException(None, name, "variable %s not found" % name)
inmanta.ast.NotFoundException: variable value not found (reported in implement __config__::A using a when true (./main.cf:16:11))
```

I find it very confusing that the line referenced by the error is the implement statement selecting the implementation where the issue occurs, instead of the line in the implementation where the variable is accessed without being defined.

Here is the project used to trigger the issue:
[confusing-error.zip](https://github.com/inmanta/inmanta-core/files/9784248/confusing-error.zip)

**Comment by edvgui** [comment]
```console
(tmp-af7dbc22f361108) guillaume@latitude-5411:~/.virtualenvs/tmp-af7dbc22f361108/confusing-error$ inmanta --version
inmanta.config           WARNING Config name token not defined in section server_rest_transport
Inmanta Service Orchestrator (Open Source Edition): 2022.3.1.dev20221014033457
Compiler version: 2022.4
Extensions:
    * core: 7.1.1.dev20221014033540
```

**Comment by sanderr** [comment]
This behavior seems to have changed somewhere between `inmanta-core` `5.1.1` and `6.3.0`.
