### ISSUE TITLE
Support string comparison

### ISSUE THREAD

**Issue by edvgui** [inmanta/inmanta-core#4986]
For now, only float and integer can be used with `>` and `<` operators.  It would be nice to add support for strings as well.  The expected behavior would be the same as python's string comparison.

```
entity A:
	string name
end


implementation a for A:
	value = self.name > "a" ? 0 : 1
	std::print(value)
end

implement A using a

A(name="a")
```

Current behavior:
```console
(tmp-af7dbc22f361108) guillaume@latitude-5411:~/.virtualenvs/tmp-af7dbc22f361108/confusing-error$ inmanta -X compile
Traceback (most recent call last):
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/app.py", line 870, in app
    options.func(options)
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/app.py", line 408, in compile_project
    do_compile()
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/compiler/__init__.py", line 76, in do_compile
    compiler.handle_exception(e)
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/compiler/__init__.py", line 250, in handle_exception
    self._handle_exception_export(e)
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/compiler/__init__.py", line 256, in _handle_exception_export
    raise exception
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/compiler/__init__.py", line 248, in handle_exception
    self._handle_exception_datatrace(exception)
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/compiler/__init__.py", line 260, in _handle_exception_datatrace
    raise exception
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/compiler/__init__.py", line 72, in do_compile
    success = sched.run(compiler, statements, blocks)
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/execute/scheduler.py", line 419, in run
    next.execute()
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/execute/runtime.py", line 994, in execute
    raise e
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/execute/runtime.py", line 989, in execute
    self.resumer.resume(self.requires, self.resolver, self.queue)
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/ast/statements/generator.py", line 398, in resume
    condition_value: object = self.expression.condition.execute(
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/ast/constraint/expression.py", line 160, in execute
    return self._op([x.execute(requires, resolver, queue) for x in self._arguments])
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/ast/constraint/expression.py", line 214, in _op
    return self._bin_op(*args)
  File "/home/guillaume/.virtualenvs/tmp-af7dbc22f361108/lib/python3.9/site-packages/inmanta/ast/constraint/expression.py", line 442, in _bin_op
    raise TypingException(self, "Can only compare numbers.")
inmanta.ast.TypingException: Can only compare numbers. (reported in <inmanta.ast.statements.generator.ConditionalExpressionResumer object at 0x7f34fb41a8e0> (./main.cf:7))
```

Expected behavior:
```console
(tmp-af7dbc22f361108) guillaume@latitude-5411:~/.virtualenvs/tmp-af7dbc22f361108/confusing-error$ inmanta -X compile
1
```
[confusing-error.zip](https://github.com/inmanta/inmanta-core/files/9784360/confusing-error.zip)

Small project to run the example:

**Comment by edvgui** [comment]
```console
(tmp-af7dbc22f361108) guillaume@latitude-5411:~/.virtualenvs/tmp-af7dbc22f361108/confusing-error$ inmanta --version
inmanta.config           WARNING Config name token not defined in section server_rest_transport
Inmanta Service Orchestrator (Open Source Edition): 2022.3.1.dev20221014033457
Compiler version: 2022.4
Extensions:
    * core: 7.1.1.dev20221014033540
```
