### ISSUE TITLE
Improve exception on index collision

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta-core#5075]
# Problem

On this model

```
entity A:
    string name
    int id
end

implement A using std::none

index A(name)
index A(id)

A(name="one",id=1)
A(name="two",id=2)
A(name="one", id=2)
```
We get this error

```
Traceback (most recent call last):
  File "/home/wouter/projects/inmanta/src/inmanta/app.py", line 780, in app
    options.func(options)
  File "/home/wouter/projects/inmanta/src/inmanta/app.py", line 355, in compile_project
    do_compile()
  File "/home/wouter/projects/inmanta/src/inmanta/compiler/__init__.py", line 72, in do_compile
    success = sched.run(compiler, statements, blocks)
  File "/home/wouter/projects/inmanta/src/inmanta/execute/scheduler.py", line 332, in run
    next.execute()
  File "/home/wouter/projects/inmanta/src/inmanta/execute/runtime.py", line 718, in execute
    self._unsafe_execute()
  File "/home/wouter/projects/inmanta/src/inmanta/execute/runtime.py", line 712, in _unsafe_execute
    value = self.expression.execute(requires, self.resolver, self.queue_scheduler)
  File "/home/wouter/projects/inmanta/src/inmanta/ast/statements/generator.py", line 577, in execute
    raise Exception("Inconsistent indexes detected!")
Exception: Inconsistent indexes detected!

Process finished with exit code 1
```
This error provides no clue as to what is going on where. 

# Solution

This error should be improved, potentially with an explainer 
The feedback should be something like

```
The constructor `A(name="one", id=2) (lnr)` matches different instances in different indexes:
 - `index A(name)` matches `__config__::A (instantiated at ./main.cf:11)`
 - `index A(id)` matches `__config__::A (instantiated at ./main.cf:12)`
```

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/5075?planning-poker) with Zenhub @FloLey @Hugo-Inmanta @sanderr @arnaudsjs
