### ISSUE TITLE
inmanta module freeze raises exception

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta-core#5631]
When the `inmanta module freeze` command is executed on the module from the module template, it raises the following exception:
```
(tmp)  /tmp/test-module  inmanta -X module freeze -o -
Traceback (most recent call last):
  File "/home/arnaud/.virtualenvs/tmp/lib/python3.9/site-packages/inmanta/app.py", line 874, in app
    options.func(options)
  File "/home/arnaud/.virtualenvs/tmp/lib/python3.9/site-packages/inmanta/app.py", line 446, in modules
    tool.execute(options.cmd, options)
  File "/home/arnaud/.virtualenvs/tmp/lib/python3.9/site-packages/inmanta/moduletool.py", line 148, in execute
    method(**outargs)
  File "/home/arnaud/.virtualenvs/tmp/lib/python3.9/site-packages/inmanta/moduletool.py", line 1070, in freeze
    newconfig = yaml.safe_load(fd)
  File "/home/arnaud/.virtualenvs/tmp/lib64/python3.9/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/home/arnaud/.virtualenvs/tmp/lib64/python3.9/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/home/arnaud/.virtualenvs/tmp/lib64/python3.9/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/home/arnaud/.virtualenvs/tmp/lib64/python3.9/site-packages/yaml/composer.py", line 39, in get_single_node
    if not self.check_event(StreamEndEvent):
  File "/home/arnaud/.virtualenvs/tmp/lib64/python3.9/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/arnaud/.virtualenvs/tmp/lib64/python3.9/site-packages/yaml/parser.py", line 171, in parse_document_start
    raise ParserError(None, None,
yaml.parser.ParserError: expected '<document start>', but found '<scalar>'
  in "/tmp/test-module/setup.cfg", line 2, column 1

```

**Comment by sanderr** [comment]
This command attempts to load the module metadata file as yaml. For v2 modules this is `setup.cfg`, which is not a yaml file.
