### ISSUE TITLE
use instance identity for error output

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#5633]
# Suggestion

Introduce the concept of an identity attribute or index to core, which can then be used in error messages to more clearly point out a specific instance. If it is not set, keep old behavior.

# Motivation

Imagine an lsm-like scenario where many instances are created in an implementation or a for loop. The line number in a potential error message doesn't help much in identifying the faulty instance(s) because many instances are created at this same line. In this case it would be very useful to have the error message contain a human-readable identification of the instance.

Consider the model below:
```
entity MyService:
    string name
    int count
end


entity MyResource:
    string name
end
MyService.resource [1] -- MyResource.service [1]
index MyResource(name)


implementation create_resource for MyService:
    self.resource = MyResource(name=self.name)
end


implement MyService using create_resource
implement MyResource using std::none


service_inventory = [
    {
        "name": "myname",
        "count": 1,
    }, {
        "name": "Arthur Dent",
        "count": 42,
    }, {
        "name": "myname",
        "count": 0,
    },
]


for service in service_inventory:
    MyService(**service)
end
```

It creates some instances which are refined into some resources. The resource entity has an index on an attribute that comes from the service, but the service entity does not have this index. Therefore, while two of the input dictionaries are incompatible, this will not result in a double assignment error on the service instance (which would be a clearer error message), but it will result in a double set exception on the `MyResource.service` relation due to the reverse assignment in the `MyService` constructor, combined with an index match on the RHS.

This is the output:
```
Traceback (most recent call last):
  File "/home/sander/documents/projects/inmanta/inmanta-core/src/inmanta/execute/runtime.py", line 1213, in set_attribute
    self.slots[name].set_value(value, location, recur)
  File "/home/sander/documents/projects/inmanta/inmanta-core/src/inmanta/execute/runtime.py", line 377, in set_value
    raise DoubleSetException(self, None, value, location)
inmanta.ast.DoubleSetException: value set twice:
	old value: __config__::MyService (instantiated at /home/sander/documents/projects/inmanta/model-test/main.cf:38)
		set at /home/sander/documents/projects/inmanta/model-test/main.cf:15
	new value: __config__::MyService (instantiated at /home/sander/documents/projects/inmanta/model-test/main.cf:38)
		set at /home/sander/documents/projects/inmanta/model-test/main.cf:15
 (reported in self.resource = Construct(MyResource) (/home/sander/documents/projects/inmanta/model-test/main.cf:15))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sander/documents/projects/inmanta/inmanta-core/src/inmanta/app.py", line 874, in app
    options.func(options)
  File "/home/sander/documents/projects/inmanta/inmanta-core/src/inmanta/app.py", line 412, in compile_project
    do_compile()
  File "/home/sander/documents/projects/inmanta/inmanta-core/src/inmanta/compiler/__init__.py", line 80, in do_compile
    compiler.handle_exception(e)
  File "/home/sander/documents/projects/inmanta/inmanta-core/src/inmanta/compiler/__init__.py", line 254, in handle_exception
    self._handle_exception_export(e)
  File "/home/sander/documents/projects/inmanta/inmanta-core/src/inmanta/compiler/__init__.py", line 260, in _handle_exception_export
    raise exception
  File "/home/sander/documents/projects/inmanta/inmanta-core/src/inmanta/compiler/__init__.py", line 252, in handle_exception
    self._handle_exception_datatrace(exception)
  File "/home/sander/documents/projects/inmanta/inmanta-core/src/inmanta/compiler/__init__.py", line 264, in _handle_exception_datatrace
    raise exception
  File "/home/sander/documents/projects/inmanta/inmanta-core/src/inmanta/compiler/__init__.py", line 75, in do_compile
    success = sched.run(compiler, statements, blocks)
  File "/home/sander/documents/projects/inmanta/inmanta-core/src/inmanta/execute/scheduler.py", line 406, in run
    next.execute()
  File "/home/sander/documents/projects/inmanta/inmanta-core/src/inmanta/ast/statements/assign.py", line 325, in execute
    ExecutionUnit._unsafe_execute(self)
  File "/home/sander/documents/projects/inmanta/inmanta-core/src/inmanta/execute/runtime.py", line 915, in _unsafe_execute
    self.result.set_value(value, self.expression.location)
  File "/home/sander/documents/projects/inmanta/inmanta-core/src/inmanta/execute/runtime.py", line 388, in set_value
    value.set_attribute(self.attribute.end.name, self.myself, location, False)
  File "/home/sander/documents/projects/inmanta/inmanta-core/src/inmanta/execute/runtime.py", line 1215, in set_attribute
    raise AttributeException(self, self, name, cause=e)
inmanta.ast.AttributeException: Could not set attribute `service` on instance `__config__::MyResource (instantiated at /home/sander/documents/projects/inmanta/model-test/main.cf:15,/home/sander/documents/projects/inmanta/model-test/main.cf:15)` (reported in __config__::MyResource (instantiated at /home/sander/documents/projects/inmanta/model-test/main.cf:15,/home/sander/documents/projects/inmanta/model-test/main.cf:15) (/home/sander/documents/projects/inmanta/model-test/main.cf:15))
```

The message references the three relevant service instances but in a very ambiguous way. This makes it way more difficult to assess which service instances are relevant for this error. In turn, this makes it more difficult to figure out the root cause, because it can't be pinned down to specific values.

## Real-world use case

This ticket was created based on [an actual error at BICS](https://code.inmanta.com/solutions/bics/bics_ce/-/issues/177#note_56977).

**Comment by sanderr** [comment]
discussed in planning meeting: agreed on general proposal. I will dig up suggestion from Slack to infer identity from an index, and make the ticket more concrete, then it can be scheduled.

**Comment by sanderr** [comment]
Related discussions:
- https://inmanta.slack.com/archives/CKRF0C8R3/p1686640932168409
- https://inmanta.slack.com/archives/CKRF0C8R3/p1689773179848229?thread_ts=1689771099.317199&cid=CKRF0C8R3
