### ISSUE TITLE
Bad dependency breaks the compiler

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta-core#5665]
I try to compile a project that worked for years. When I compile it now I get the following output:

```
❯ inmanta -vvv compile
inmanta.compiler         DEBUG   Starting compile
inmanta.warnings         WARNING InmantaWarning: Loaded V1 module ssh. The use of V1 modules is deprecated. Use the equivalent V2 module instead.
inmanta.warnings         WARNING InmantaWarning: Loaded V1 module ip. The use of V1 modules is deprecated. Use the equivalent V2 module instead.
inmanta.module           WARNING Module std is installed as a V1 module and a V2 module: V1 will be ignored.
inmanta.warnings         WARNING InmantaWarning: Loaded V1 module net. The use of V1 modules is deprecated. Use the equivalent V2 module instead.
inmanta.warnings         WARNING InmantaWarning: Loaded V1 module redhat. The use of V1 modules is deprecated. Use the equivalent V2 module instead.
inmanta.warnings         WARNING InmantaWarning: Loaded V1 module infra. The use of V1 modules is deprecated. Use the equivalent V2 module instead.
inmanta.warnings         WARNING InmantaWarning: Loaded V1 module exec. The use of V1 modules is deprecated. Use the equivalent V2 module instead.
inmanta.warnings         WARNING InmantaWarning: Loaded V1 module cron. The use of V1 modules is deprecated. Use the equivalent V2 module instead.
inmanta.module           WARNING Module lsm is installed as a V1 module and a V2 module: V1 will be ignored.
inmanta.warnings         WARNING InmantaWarning: Loaded V1 module openstack. The use of V1 modules is deprecated. Use the equivalent V2 module instead.
inmanta.warnings         WARNING InmantaWarning: Loaded V1 module platform. The use of V1 modules is deprecated. Use the equivalent V2 module instead.
inmanta.warnings         WARNING InmantaWarning: Loaded V1 module yum. The use of V1 modules is deprecated. Use the equivalent V2 module instead.
inmanta.warnings         WARNING InmantaWarning: Loaded V1 module user. The use of V1 modules is deprecated. Use the equivalent V2 module instead.
inmanta.warnings         WARNING InmantaWarning: Loaded V1 module systemd. The use of V1 modules is deprecated. Use the equivalent V2 module instead.
inmanta.warnings         WARNING InmantaWarning: Loaded V1 module cloudflared. The use of V1 modules is deprecated. Use the equivalent V2 module instead.
inmanta.warnings         WARNING InmantaWarning: Loaded V1 module influx. The use of V1 modules is deprecated. Use the equivalent V2 module instead.
inmanta.warnings         WARNING InmantaWarning: Loaded V1 module nginx. The use of V1 modules is deprecated. Use the equivalent V2 module instead.
inmanta.warnings         WARNING InmantaWarning: Loaded V1 module devpi. The use of V1 modules is deprecated. Use the equivalent V2 module instead.
inmanta.warnings         WARNING InmantaWarning: Loaded V1 module iso. The use of V1 modules is deprecated. Use the equivalent V2 module instead.
inmanta.warnings         WARNING InmantaWarning: Loaded V1 module pki. The use of V1 modules is deprecated. Use the equivalent V2 module instead.
inmanta.warnings         WARNING InmantaWarning: Loaded V1 module keycloak. The use of V1 modules is deprecated. Use the equivalent V2 module instead.
inmanta.warnings         WARNING InmantaWarning: Loaded V1 module java. The use of V1 modules is deprecated. Use the equivalent V2 module instead.
inmanta.warnings         WARNING InmantaWarning: Loaded V1 module postgresql. The use of V1 modules is deprecated. Use the equivalent V2 module instead.
inmanta.warnings         WARNING InmantaWarning: Loaded V1 module apt. The use of V1 modules is deprecated. Use the equivalent V2 module instead.
inmanta.warnings         WARNING InmantaWarning: Loaded V1 module grafana. The use of V1 modules is deprecated. Use the equivalent V2 module instead.
inmanta.warnings         WARNING InmantaWarning: Loaded V1 module ntp. The use of V1 modules is deprecated. Use the equivalent V2 module instead.
inmanta.warnings         WARNING InmantaWarning: Loaded V1 module postfix. The use of V1 modules is deprecated. Use the equivalent V2 module instead.
inmanta.module           DEBUG   Parsing took 0.187757 seconds
inmanta.parser.cache     DEBUG   Compiler cache observed 59 hits and 0 misses (100%)
inmanta.module           INFO    verifying project
Expected closing RIGHT_PARENTHESIS
    tinycss2 (>=1.1.0<1.2) ; extra == 'css'
             ~~~~~~~~^
```

When I grep for tinycss2 I am unable to find where it comes from. The error should provide more context and not should except through the compiler.

With -X I get the following stacktrace:

```
Traceback (most recent call last):
  File "/home/bart/.virtualenvs/core/lib64/python3.9/site-packages/pkg_resources/__init__.py", line 3030, in _dep_map
    return self.__dep_map
  File "/home/bart/.virtualenvs/core/lib64/python3.9/site-packages/pkg_resources/__init__.py", line 2826, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bart/.virtualenvs/core/lib64/python3.9/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 35, in __init__
    parsed = parse_requirement(requirement_string)
  File "/home/bart/.virtualenvs/core/lib64/python3.9/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 64, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
  File "/home/bart/.virtualenvs/core/lib64/python3.9/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 82, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
  File "/home/bart/.virtualenvs/core/lib64/python3.9/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 120, in _parse_requirement_details
    specifier = _parse_specifier(tokenizer)
  File "/home/bart/.virtualenvs/core/lib64/python3.9/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 209, in _parse_specifier
    tokenizer.consume("WS")
  File "/usr/lib64/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/home/bart/.virtualenvs/core/lib64/python3.9/site-packages/pkg_resources/_vendor/packaging/_tokenizer.py", line 183, in enclosing_tokens
    self.raise_syntax_error(
  File "/home/bart/.virtualenvs/core/lib64/python3.9/site-packages/pkg_resources/_vendor/packaging/_tokenizer.py", line 163, in raise_syntax_error
    raise ParserSyntaxError(
pkg_resources.extern.packaging._tokenizer.ParserSyntaxError: Expected closing RIGHT_PARENTHESIS
    tinycss2 (>=1.1.0<1.2) ; extra == 'css'
             ~~~~~~~~^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bart/workspace/inmanta-core/src/inmanta/app.py", line 874, in app
    options.func(options)
  File "/home/bart/workspace/inmanta-core/src/inmanta/app.py", line 412, in compile_project
    do_compile()
  File "/home/bart/workspace/inmanta-core/src/inmanta/compiler/__init__.py", line 69, in do_compile
    (statements, blocks) = compiler.compile()
  File "/home/bart/workspace/inmanta-core/src/inmanta/compiler/__init__.py", line 193, in compile
    project.load()
  File "/home/bart/workspace/inmanta-core/src/inmanta/module.py", line 2056, in load
    self.verify()
  File "/home/bart/workspace/inmanta-core/src/inmanta/module.py", line 2386, in verify
    self.verify_python_requires()
  File "/home/bart/workspace/inmanta-core/src/inmanta/module.py", line 2442, in verify_python_requires
    env.ActiveEnv.check(strict_scope=re.compile(f"{ModuleV2.PKG_NAME_PREFIX}.*"), constraints=constraints)
  File "/home/bart/workspace/inmanta-core/src/inmanta/env.py", line 981, in check
    constraint_violations, constraint_violations_strict = cls.get_constraint_violations_for_check(strict_scope, constraints)
  File "/home/bart/workspace/inmanta-core/src/inmanta/env.py", line 918, in get_constraint_violations_for_check
    installed_constraints: abc.Set[OwnedRequirement] = frozenset(
  File "/home/bart/workspace/inmanta-core/src/inmanta/env.py", line 921, in <genexpr>
    for requirement in dist_info.requires()
  File "/home/bart/.virtualenvs/core/lib64/python3.9/site-packages/pkg_resources/__init__.py", line 2746, in requires
    dm = self._dep_map
  File "/home/bart/.virtualenvs/core/lib64/python3.9/site-packages/pkg_resources/__init__.py", line 3032, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/home/bart/.virtualenvs/core/lib64/python3.9/site-packages/pkg_resources/__init__.py", line 3042, in _compute_dependencies
    reqs.extend(parse_requirements(req))
  File "/home/bart/.virtualenvs/core/lib64/python3.9/site-packages/pkg_resources/__init__.py", line 3095, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/home/bart/.virtualenvs/core/lib64/python3.9/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 37, in __init__
    raise InvalidRequirement(str(e)) from e
pkg_resources.extern.packaging.requirements.InvalidRequirement: Expected closing RIGHT_PARENTHESIS
    tinycss2 (>=1.1.0<1.2) ; extra == 'css'
```

**Comment by bartv** [comment]
This was caused by the bleach library in my venv. No idea how it got there.

**Comment by sanderr** [comment]
I'm not sure how we should deal with this. `bleach==5.0.0` just contains an invalid requirement. I'm surprised pip manages to install it at all. Looks like it just ignores the requirement.
I agree that ideally we should not fail on this, and if we do we should be more clear as to the cause, but off the top of my head I don't see how we should approach it instead.
