### ISSUE TITLE
investigate timeout on license component status

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#5933]
There was a timeout on the server status page of the management orchestrator for the license component. The log contained this trace:

```
2023-04-27 08:43:18,213 ERROR    inmanta.server.server The following error occured while trying to determine the status of slice license.license
Traceback (most recent call last):
  File "src/inmanta_license/license.py", line 806, in get_status
  File "src/inmanta_license/license.py", line 788, in get_license_metrics
  File "/opt/inmanta/lib64/python3.9/site-packages/inmanta/data/__init__.py", line 4534, in get_resources_report
    async for record in con.cursor(query, *values):
  File "/opt/inmanta/lib64/python3.9/site-packages/asyncpg/cursor.py", line 223, in __anext__
    buffer = await self._bind_exec(self._prefetch, self._timeout)
  File "/opt/inmanta/lib64/python3.9/site-packages/asyncpg/cursor.py", line 129, in _bind_exec
    buffer, _, self._exhausted = await protocol.bind_execute(
  File "asyncpg/protocol/protocol.pyx", line 201, in bind_execute
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/inmanta/lib64/python3.9/site-packages/inmanta/server/server.py", line 134, in collect_for_slice
    return SliceStatus(name=slice_name, status=await asyncio.wait_for(slice.get_status(), 0.1))
  File "/usr/lib64/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
```

The timeout should be investigated and appropriate action taken.

**Comment by sanderr** [comment]
Discussed in planning meeting at 2023-05-02: probably a badly constructed query.
