### ISSUE TITLE
F-string unusable in conditionnal expression

### ISSUE THREAD

**Issue by edvgui** [inmanta/inmanta-core#6449]
The following model fails to compile:
```
a = "a"
aa = a == "b" ? a : f"{a}{a}"
std::print(aa)
```
It gives the following error:
```
Traceback (most recent call last):
  File "/home/guillaume/.virtualenvs/edvgui_project/lib/python3.9/site-packages/inmanta/app.py", line 894, in app
    options.func(options)
  File "/home/guillaume/.virtualenvs/edvgui_project/lib/python3.9/site-packages/inmanta/app.py", line 412, in compile_project
    do_compile()
  File "/home/guillaume/.virtualenvs/edvgui_project/lib/python3.9/site-packages/inmanta/compiler/__init__.py", line 81, in do_compile
    compiler.handle_exception(e)
  File "/home/guillaume/.virtualenvs/edvgui_project/lib/python3.9/site-packages/inmanta/compiler/__init__.py", line 255, in handle_exception
    self._handle_exception_export(e)
  File "/home/guillaume/.virtualenvs/edvgui_project/lib/python3.9/site-packages/inmanta/compiler/__init__.py", line 261, in _handle_exception_export
    raise exception
  File "/home/guillaume/.virtualenvs/edvgui_project/lib/python3.9/site-packages/inmanta/compiler/__init__.py", line 253, in handle_exception
    self._handle_exception_datatrace(exception)
  File "/home/guillaume/.virtualenvs/edvgui_project/lib/python3.9/site-packages/inmanta/compiler/__init__.py", line 265, in _handle_exception_datatrace
    raise exception
  File "/home/guillaume/.virtualenvs/edvgui_project/lib/python3.9/site-packages/inmanta/compiler/__init__.py", line 76, in do_compile
    success = sched.run(compiler, statements, blocks)
  File "/home/guillaume/.virtualenvs/edvgui_project/lib/python3.9/site-packages/inmanta/execute/scheduler.py", line 417, in run
    next.execute()
  File "/home/guillaume/.virtualenvs/edvgui_project/lib/python3.9/site-packages/inmanta/execute/runtime.py", line 1044, in execute
    raise e
  File "/home/guillaume/.virtualenvs/edvgui_project/lib/python3.9/site-packages/inmanta/execute/runtime.py", line 1039, in execute
    self.resumer.resume(self.requires, self.resolver, self.queue)
  File "/home/guillaume/.virtualenvs/edvgui_project/lib/python3.9/site-packages/inmanta/ast/statements/generator.py", line 433, in resume
    subexpression.requires_emit(resolver, queue),
  File "/home/guillaume/.virtualenvs/edvgui_project/lib/python3.9/site-packages/inmanta/ast/variables.py", line 89, in requires_emit
    requires[self.name] = resolver.lookup(self.full_name)
  File "/home/guillaume/.virtualenvs/edvgui_project/lib/python3.9/site-packages/inmanta/execute/runtime.py", line 1171, in lookup
    return self.resolver.lookup(name, root)
  File "/home/guillaume/.virtualenvs/edvgui_project/lib/python3.9/site-packages/inmanta/execute/runtime.py", line 1081, in lookup
    return ns.lookup(name)
  File "/home/guillaume/.virtualenvs/edvgui_project/lib/python3.9/site-packages/inmanta/ast/__init__.py", line 367, in lookup
    return self.get_scope().direct_lookup(name)
  File "/home/guillaume/.virtualenvs/edvgui_project/lib/python3.9/site-packages/inmanta/execute/runtime.py", line 1177, in direct_lookup
    raise NotFoundException(None, name, "variable %s not found" % name)
inmanta.ast.NotFoundException: variable f not found (reported in <inmanta.ast.statements.generator.ConditionalExpressionResumer object at 0x7fe409b51280> (./f_bug.cf:2))
```

I would expect it to print the string `aa`

**Comment by edvgui** [comment]
Nevermind, my compiler version was not old enough
