### ISSUE TITLE
environment_modify raises a 500 for: 'name field is required'

### ISSUE THREAD

**Issue by edvgui** [inmanta/inmanta-core#6548]
```
        updates: dict[str, object] = dict(name=self.name)
        if self.project is not None and current_project.name != self.name:
            # We care about the project name and it is not a match
            # We make sure the project with the desired name exists and
            # assign our environment to it
            updates["project_id"] = self.configure_project(client).id
    
        if len(updates) > 0:
            # Apply the updates
            result = client.environment_modify(
                id=self.id,
                **updates,
            )
    
>           assert result.code in range(200, 300), str(result.result)
E           AssertionError: {'message': "An unexpected error occurred in the server while processing the request: ('name field is required',)"}
E           assert 500 in range(200, 300)
E            +  where 500 = <inmanta.protocol.common.Result object at 0x7fa9b6109490>.code
E            +  and   range(200, 300) = range(200, 300)
```

I met this strange issue:
1. The name is provided as argument, in the update dict
2. The response from the server is a 500, if this is user input issue it should be 4xx

**Comment by arnaudsjs** [comment]
In the above-mentioned code snippet, the `updates` dictionary contained the key-value pair `name=None`.

Server-side stack trace:

```
Traceback (most recent call last):
  File "/opt/inmanta/lib64/python3.11/site-packages/inmanta/protocol/rest/__init__.py", line 537, in _execute_call
    result = await config.handler(**arguments.call_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/inmanta/lib64/python3.11/site-packages/inmanta/server/services/environmentservice.py", line 451, in environment_modify
    await env.update_fields(connection=None, **fields)
  File "/opt/inmanta/lib64/python3.11/site-packages/inmanta/data/__init__.py", line 1749, in update_fields
    setattr(self, name, value)
  File "/opt/inmanta/lib64/python3.11/site-packages/inmanta/data/__init__.py", line 1526, in __setattr__
    field.validate(name, value)
  File "/opt/inmanta/lib64/python3.11/site-packages/inmanta/data/__init__.py", line 1167, in validate
    raise TypeError("%s field is required" % name)
TypeError: name field is required
2023-09-28 07:00:01,513 WARNING  inmanta.protocol.rest.server Received an exception with status code 500 and message {'message': "An unexpected error occurred in the server while processing the request: ('name field is required',)"}
```

**Comment by sanderr** [comment]
Conclusion: return code should be 400, other than that the current behavior is OK.
