### ISSUE TITLE
Compiler exception fails

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta-core#6941]
```
❯ inmanta -vvv export -v -X
compiler       WARNING TypeDeprecationWarning: Type 'number' is deprecated, use 'float' or 'int' instead
exporter       WARNING Compilation of model failed.
exporter       WARNING Empty deployment model.

================================================================================================================================================================= EXCEPTION TRACE =================================================================================================================================================================
Traceback (most recent call last):
  File "/home/bart/.virtualenvs/mpn/lib64/python3.11/site-packages/inmanta/ast/entity.py", line 526, in normalize
    self.statements.normalize()
  File "/home/bart/.virtualenvs/mpn/lib64/python3.11/site-packages/inmanta/ast/blocks.py", line 72, in normalize
    s.normalize()
  File "/home/bart/.virtualenvs/mpn/lib64/python3.11/site-packages/inmanta/ast/statements/generator.py", line 227, in normalize
    self.module.normalize()
  File "/home/bart/.virtualenvs/mpn/lib64/python3.11/site-packages/inmanta/ast/blocks.py", line 72, in normalize
    s.normalize()
  File "/home/bart/.virtualenvs/mpn/lib64/python3.11/site-packages/inmanta/ast/statements/assign.py", line 228, in normalize
    self.rhs.normalize(lhs_attribute=AttributeAssignmentLHS(self.instance, self.attribute_name))
  File "/home/bart/.virtualenvs/mpn/lib64/python3.11/site-packages/inmanta/ast/statements/assign.py", line 92, in normalize
    item.normalize(lhs_attribute=lhs_attribute)
  File "/home/bart/.virtualenvs/mpn/lib64/python3.11/site-packages/inmanta/ast/statements/generator.py", line 911, in normalize
    self._normalize_rhs(inindex)
  File "/home/bart/.virtualenvs/mpn/lib64/python3.11/site-packages/inmanta/ast/statements/generator.py", line 875, in _normalize_rhs
    v.normalize(
  File "/home/bart/.virtualenvs/mpn/lib64/python3.11/site-packages/inmanta/ast/statements/generator.py", line 911, in normalize
    self._normalize_rhs(inindex)
  File "/home/bart/.virtualenvs/mpn/lib64/python3.11/site-packages/inmanta/ast/statements/generator.py", line 875, in _normalize_rhs
    v.normalize(
  File "/home/bart/.virtualenvs/mpn/lib64/python3.11/site-packages/inmanta/ast/statements/generator.py", line 286, in normalize
    self.iterable.normalize()
  File "/home/bart/.virtualenvs/mpn/lib64/python3.11/site-packages/inmanta/ast/statements/assign.py", line 92, in normalize
    item.normalize(lhs_attribute=lhs_attribute)
  File "/home/bart/.virtualenvs/mpn/lib64/python3.11/site-packages/inmanta/ast/statements/generator.py", line 670, in normalize
    self.condition.normalize()
  File "/home/bart/.virtualenvs/mpn/lib64/python3.11/site-packages/inmanta/ast/statements/__init__.py", line 522, in normalize
    child.normalize()
  File "/home/bart/.virtualenvs/mpn/lib64/python3.11/site-packages/inmanta/ast/variables.py", line 77, in normalize
    self.namespace.lookup_namespace(split[0])
  File "/home/bart/.virtualenvs/mpn/lib64/python3.11/site-packages/inmanta/ast/__init__.py", line 381, in lookup_namespace
    raise NotFoundException(None, name, f"Namespace {name} not found. Try importing it with `import {name}`")
inmanta.ast.NotFoundException: Namespace athonet_mpn::const not found. Try importing it with `import athonet_mpn::const` (reported in athonet_mpn::const::no_v6_prefix (/home/bart/workspace/projects/athonet/athonet_mpn/model/domain/core/components.cf:2603:52))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bart/.virtualenvs/mpn/lib64/python3.11/site-packages/inmanta/app.py", line 672, in capture
    yield self
  File "/home/bart/.virtualenvs/mpn/lib64/python3.11/site-packages/inmanta/app.py", line 617, in export
    (types, scopes) = do_compile()
                      ^^^^^^^^^^^^
  File "/home/bart/.virtualenvs/mpn/lib64/python3.11/site-packages/inmanta/compiler/__init__.py", line 77, in do_compile
    success = sched.run(compiler, statements, blocks)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bart/.virtualenvs/mpn/lib64/python3.11/site-packages/inmanta/execute/scheduler.py", line 362, in run
    self.define_types(compiler, statements, blocks)
  File "/home/bart/.virtualenvs/mpn/lib64/python3.11/site-packages/inmanta/execute/scheduler.py", line 258, in define_types
    t.normalize()
  File "/home/bart/.virtualenvs/mpn/lib64/python3.11/site-packages/inmanta/ast/entity.py", line 528, in normalize
    e.set_location(self.location, False)
TypeError: CompilerException.set_location() takes 2 positional arguments but 3 were given

=============================================================================================================================================================== COMPILATION FAILURE ===============================================================================================================================================================
Error: CompilerException.set_location() takes 2 positional arguments but 3 were given
```

It is caused by referencing something that is not imported in a guard inside a list comprehension

![image](https://github.com/inmanta/inmanta-core/assets/10819/6fcf2e63-4abe-4d30-91e0-f3d077d652b5)

**Comment by sanderr** [comment]
Should be a call to `set_statement` instead of `set_location`.
