### ISSUE TITLE
"NoneType object is not iterable" error on dryrun_request call

### ISSUE THREAD

**Issue by jptrindade** [inmanta/inmanta-core#7065]
When executing a `dryrun_request` with existing tid and id I got this error. When executing a dryrun using the orchestrator directly it seems to work.

```
remote_orchestrator.client.dryrun_request(tid=lsm_project.environment, id=111)
<inmanta.protocol.common.Result object at 0x7f04cd428950>
special variables
function variables
code:
500
result:
{'message': 'An unexpected error ...terable",)'}
special variables
function variables
'message':
'An unexpected error occurred in the server while processing the request: ("\'NoneType\' object is not iterable",)'
len():
1
set_result:
{'message': 'An unexpected error ...terable",)'}
_callback:
None
_result:
{'message': 'An unexpected error ...terable",)'}
```

```
2024-01-29 12:40:59,715 inmanta.protocol.rest    DEBUG   Calling method <bound method DyrunService.dryrun_request of <inmanta.server.services.dryrunservice.DyrunService object at 0x7fdc47661290>>(version_id='111', env='<inmant...')
2024-01-29 12:40:59,869 inmanta.protocol.rest.serverDEBUG   HTTP version of request: HTTP/1.1
2024-01-29 12:40:59,878 inmanta.protocol.rest    DEBUG   Calling method <bound method DyrunService.dryrun_update of <inmanta.server.services.dryrunservice.DyrunService object at 0x7fdc47661290>>(resource='netbox:...', changes='{}', dryrun_id='50b7b59...', env='<inmant...')
2024-01-29 12:40:59,915 tornado.access           INFO    200 PUT /api/v1/dryrun/50b7b591-47fb-47e0-a992-87170f2db500 (127.0.0.1) 53.25ms
2024-01-29 12:40:59,921 inmanta.protocol.rest    ERROR   An exception occured during the request.
                                                         Traceback (most recent call last):
                                                           File "/opt/inmanta/lib64/python3.11/site-packages/inmanta/protocol/rest/__init__.py", line 554, in _execute_call
                                                             result = await config.handler(**arguments.call_args)
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                           File "/opt/inmanta/lib64/python3.11/site-packages/inmanta/server/services/dryrunservice.py", line 70, in dryrun_request
                                                             dryrun = await self.create_dryrun(env, version_id, model)
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                           File "/opt/inmanta/lib64/python3.11/site-packages/inmanta/server/services/dryrunservice.py", line 96, in create_dryrun
                                                             undeployable_version_ids = [ResourceVersionIdStr(rid + ",v=%s" % version_id) for rid in undeployable_ids]
                                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                         TypeError: 'NoneType' object is not iterable
2024-01-29 12:40:59,924 inmanta.protocol.rest.serverWARNING Received an exception with status code 500 and message {'message': 'An unexpected error occurred in the server while processing the request: ("\'NoneType\' object is not iterable",)'}
2024-01-29 12:40:59,934 tornado.access           ERROR   500 POST /api/v1/dryrun/111 (192.168.25.250) 223.72ms
```

**Comment by jptrindade** [comment]
![image](https://github.com/inmanta/inmanta-core/assets/25805946/6aaab73c-92e3-41a1-bb68-258a0326029c)
I also got it while executing the dryrun on the orchestrator

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/7065?planning-poker) with Zenhub @arnaudsjs @FloLey @Hugo-Inmanta @sanderr

**Comment by Hugo-Inmanta** [comment]
Shelving this back for now because we can't reproduce the issue.

**Comment by bartv** [comment]
@jptrindade do you have a DB dump on which this happened?
